// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: wire/v2/wire.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values intentionally match IP version numbers (4, 6).
type IPVersion int32

const (
	IPVersion_IP_VERSION_UNSPECIFIED IPVersion = 0
	IPVersion_IP_VERSION_IPV4        IPVersion = 4
	IPVersion_IP_VERSION_IPV6        IPVersion = 6
)

// Enum value maps for IPVersion.
var (
	IPVersion_name = map[int32]string{
		0: "IP_VERSION_UNSPECIFIED",
		4: "IP_VERSION_IPV4",
		6: "IP_VERSION_IPV6",
	}
	IPVersion_value = map[string]int32{
		"IP_VERSION_UNSPECIFIED": 0,
		"IP_VERSION_IPV4":        4,
		"IP_VERSION_IPV6":        6,
	}
)

func (x IPVersion) Enum() *IPVersion {
	p := new(IPVersion)
	*p = x
	return p
}

func (x IPVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_v2_wire_proto_enumTypes[0].Descriptor()
}

func (IPVersion) Type() protoreflect.EnumType {
	return &file_wire_v2_wire_proto_enumTypes[0]
}

func (x IPVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPVersion.Descriptor instead.
func (IPVersion) EnumDescriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{0}
}

// Values intentionally match IANA protocol numbers (ICMP=1, UDP=17, ICMPv6=58).
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_ICMP        Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 17
	Protocol_PROTOCOL_ICMPV6      Protocol = 58
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0:  "PROTOCOL_UNSPECIFIED",
		1:  "PROTOCOL_ICMP",
		17: "PROTOCOL_UDP",
		58: "PROTOCOL_ICMPV6",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_ICMP":        1,
		"PROTOCOL_UDP":         17,
		"PROTOCOL_ICMPV6":      58,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_v2_wire_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_wire_v2_wire_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{1}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_wire_v2_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type Info struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ProbeTtl uint32                 `protobuf:"varint,1,opt,name=probe_ttl,json=probeTtl,proto3" json:"probe_ttl,omitempty"`
	// Canonical textual IP address of the probe reply, without a port or
	// zone identifier. Absent (empty) when the probe timed out or produced
	// no reply — see ForwardingInfoElement.near_info/far_info.
	ReplyAddress string `protobuf:"bytes,2,opt,name=reply_address,json=replyAddress,proto3" json:"reply_address,omitempty"`
	// Always UTC. Absent (unset) has the same meaning as reply_address
	// being empty: no reply was received.
	SentTimestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	ReceivedTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_wire_v2_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Info) GetProbeTtl() uint32 {
	if x != nil {
		return x.ProbeTtl
	}
	return 0
}

func (x *Info) GetReplyAddress() string {
	if x != nil {
		return x.ReplyAddress
	}
	return ""
}

func (x *Info) GetSentTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SentTimestamp
	}
	return nil
}

func (x *Info) GetReceivedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return nil
}

type ICMPNextHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstHalfWord  uint32                 `protobuf:"varint,1,opt,name=first_half_word,json=firstHalfWord,proto3" json:"first_half_word,omitempty"`
	SecondHalfWord uint32                 `protobuf:"varint,2,opt,name=second_half_word,json=secondHalfWord,proto3" json:"second_half_word,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ICMPNextHeader) Reset() {
	*x = ICMPNextHeader{}
	mi := &file_wire_v2_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMPNextHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMPNextHeader) ProtoMessage() {}

func (x *ICMPNextHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMPNextHeader.ProtoReflect.Descriptor instead.
func (*ICMPNextHeader) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{2}
}

func (x *ICMPNextHeader) GetFirstHalfWord() uint32 {
	if x != nil {
		return x.FirstHalfWord
	}
	return 0
}

func (x *ICMPNextHeader) GetSecondHalfWord() uint32 {
	if x != nil {
		return x.SecondHalfWord
	}
	return 0
}

type UDPNextHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourcePort      uint32                 `protobuf:"varint,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,2,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UDPNextHeader) Reset() {
	*x = UDPNextHeader{}
	mi := &file_wire_v2_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPNextHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPNextHeader) ProtoMessage() {}

func (x *UDPNextHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPNextHeader.ProtoReflect.Descriptor instead.
func (*UDPNextHeader) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{3}
}

func (x *UDPNextHeader) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *UDPNextHeader) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

type ICMPv6NextHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstHalfWord  uint32                 `protobuf:"varint,1,opt,name=first_half_word,json=firstHalfWord,proto3" json:"first_half_word,omitempty"`
	SecondHalfWord uint32                 `protobuf:"varint,2,opt,name=second_half_word,json=secondHalfWord,proto3" json:"second_half_word,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ICMPv6NextHeader) Reset() {
	*x = ICMPv6NextHeader{}
	mi := &file_wire_v2_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMPv6NextHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMPv6NextHeader) ProtoMessage() {}

func (x *ICMPv6NextHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMPv6NextHeader.ProtoReflect.Descriptor instead.
func (*ICMPv6NextHeader) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{4}
}

func (x *ICMPv6NextHeader) GetFirstHalfWord() uint32 {
	if x != nil {
		return x.FirstHalfWord
	}
	return 0
}

func (x *ICMPv6NextHeader) GetSecondHalfWord() uint32 {
	if x != nil {
		return x.SecondHalfWord
	}
	return 0
}

type NextHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Header:
	//
	//	*NextHeader_IcmpNextHeader
	//	*NextHeader_UdpNextHeader
	//	*NextHeader_Icmpv6NextHeader
	Header        isNextHeader_Header `protobuf_oneof:"header"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextHeader) Reset() {
	*x = NextHeader{}
	mi := &file_wire_v2_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHeader) ProtoMessage() {}

func (x *NextHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHeader.ProtoReflect.Descriptor instead.
func (*NextHeader) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{5}
}

func (x *NextHeader) GetHeader() isNextHeader_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NextHeader) GetIcmpNextHeader() *ICMPNextHeader {
	if x != nil {
		if x, ok := x.Header.(*NextHeader_IcmpNextHeader); ok {
			return x.IcmpNextHeader
		}
	}
	return nil
}

func (x *NextHeader) GetUdpNextHeader() *UDPNextHeader {
	if x != nil {
		if x, ok := x.Header.(*NextHeader_UdpNextHeader); ok {
			return x.UdpNextHeader
		}
	}
	return nil
}

func (x *NextHeader) GetIcmpv6NextHeader() *ICMPv6NextHeader {
	if x != nil {
		if x, ok := x.Header.(*NextHeader_Icmpv6NextHeader); ok {
			return x.Icmpv6NextHeader
		}
	}
	return nil
}

type isNextHeader_Header interface {
	isNextHeader_Header()
}

type NextHeader_IcmpNextHeader struct {
	IcmpNextHeader *ICMPNextHeader `protobuf:"bytes,1,opt,name=icmp_next_header,json=icmpNextHeader,proto3,oneof"`
}

type NextHeader_UdpNextHeader struct {
	UdpNextHeader *UDPNextHeader `protobuf:"bytes,2,opt,name=udp_next_header,json=udpNextHeader,proto3,oneof"`
}

type NextHeader_Icmpv6NextHeader struct {
	Icmpv6NextHeader *ICMPv6NextHeader `protobuf:"bytes,3,opt,name=icmpv6_next_header,json=icmpv6NextHeader,proto3,oneof"`
}

func (*NextHeader_IcmpNextHeader) isNextHeader_Header() {}

func (*NextHeader_UdpNextHeader) isNextHeader_Header() {}

func (*NextHeader_Icmpv6NextHeader) isNextHeader_Header() {}

// AuthRequest/AuthResponse must only be exchanged over a mutually
// authenticated TLS connection. secret must never be logged.
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_wire_v2_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{6}
}

func (x *AuthRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AuthRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_wire_v2_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{7}
}

func (x *AuthResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProbingDirective struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProbingDirectiveId uint64                 `protobuf:"varint,1,opt,name=probing_directive_id,json=probingDirectiveId,proto3" json:"probing_directive_id,omitempty"`
	IpVersion          IPVersion              `protobuf:"varint,2,opt,name=ip_version,json=ipVersion,proto3,enum=wire.v2.IPVersion" json:"ip_version,omitempty"`
	Protocol           Protocol               `protobuf:"varint,3,opt,name=protocol,proto3,enum=wire.v2.Protocol" json:"protocol,omitempty"`
	AgentId            string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Canonical textual IP address, without a port or zone identifier.
	DestinationAddress string `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// TTL sent in the near-side probe. The far-side probe is sent at
	// near_ttl + 1; see ForwardingInfoElement.near_info/far_info for the
	// corresponding paired observations.
	NearTtl       uint32      `protobuf:"varint,6,opt,name=near_ttl,json=nearTtl,proto3" json:"near_ttl,omitempty"`
	NextHeader    *NextHeader `protobuf:"bytes,7,opt,name=next_header,json=nextHeader,proto3" json:"next_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbingDirective) Reset() {
	*x = ProbingDirective{}
	mi := &file_wire_v2_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbingDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbingDirective) ProtoMessage() {}

func (x *ProbingDirective) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbingDirective.ProtoReflect.Descriptor instead.
func (*ProbingDirective) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{8}
}

func (x *ProbingDirective) GetProbingDirectiveId() uint64 {
	if x != nil {
		return x.ProbingDirectiveId
	}
	return 0
}

func (x *ProbingDirective) GetIpVersion() IPVersion {
	if x != nil {
		return x.IpVersion
	}
	return IPVersion_IP_VERSION_UNSPECIFIED
}

func (x *ProbingDirective) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *ProbingDirective) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProbingDirective) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *ProbingDirective) GetNearTtl() uint32 {
	if x != nil {
		return x.NearTtl
	}
	return 0
}

func (x *ProbingDirective) GetNextHeader() *NextHeader {
	if x != nil {
		return x.NextHeader
	}
	return nil
}

type ForwardingInfoElement struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Agent              *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	ProbingDirectiveId uint64                 `protobuf:"varint,2,opt,name=probing_directive_id,json=probingDirectiveId,proto3" json:"probing_directive_id,omitempty"`
	IpVersion          IPVersion              `protobuf:"varint,3,opt,name=ip_version,json=ipVersion,proto3,enum=wire.v2.IPVersion" json:"ip_version,omitempty"`
	Protocol           Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=wire.v2.Protocol" json:"protocol,omitempty"`
	// Canonical textual IP addresses, without a port or zone identifier.
	SourceAddress      string `protobuf:"bytes,5,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress string `protobuf:"bytes,6,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// near_info/far_info are the paired near/far-TTL probe observations
	// (see ProbingDirective.near_ttl) used to detect forwarding behavior
	// between adjacent hops. Absent when the corresponding probe timed
	// out or produced no reply.
	NearInfo *Info `protobuf:"bytes,7,opt,name=near_info,json=nearInfo,proto3" json:"near_info,omitempty"`
	FarInfo  *Info `protobuf:"bytes,8,opt,name=far_info,json=farInfo,proto3" json:"far_info,omitempty"`
	// Always UTC.
	ProductionTimestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=production_timestamp,json=productionTimestamp,proto3" json:"production_timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ForwardingInfoElement) Reset() {
	*x = ForwardingInfoElement{}
	mi := &file_wire_v2_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingInfoElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingInfoElement) ProtoMessage() {}

func (x *ForwardingInfoElement) ProtoReflect() protoreflect.Message {
	mi := &file_wire_v2_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingInfoElement.ProtoReflect.Descriptor instead.
func (*ForwardingInfoElement) Descriptor() ([]byte, []int) {
	return file_wire_v2_wire_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardingInfoElement) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *ForwardingInfoElement) GetProbingDirectiveId() uint64 {
	if x != nil {
		return x.ProbingDirectiveId
	}
	return 0
}

func (x *ForwardingInfoElement) GetIpVersion() IPVersion {
	if x != nil {
		return x.IpVersion
	}
	return IPVersion_IP_VERSION_UNSPECIFIED
}

func (x *ForwardingInfoElement) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *ForwardingInfoElement) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *ForwardingInfoElement) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *ForwardingInfoElement) GetNearInfo() *Info {
	if x != nil {
		return x.NearInfo
	}
	return nil
}

func (x *ForwardingInfoElement) GetFarInfo() *Info {
	if x != nil {
		return x.FarInfo
	}
	return nil
}

func (x *ForwardingInfoElement) GetProductionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ProductionTimestamp
	}
	return nil
}

var File_wire_v2_wire_proto protoreflect.FileDescriptor

const file_wire_v2_wire_proto_rawDesc = "" +
	"\n" +
	"\x12wire/v2/wire.proto\x12\awire.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x05Agent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xd6\x01\n" +
	"\x04Info\x12\x1b\n" +
	"\tprobe_ttl\x18\x01 \x01(\rR\bprobeTtl\x12#\n" +
	"\rreply_address\x18\x02 \x01(\tR\freplyAddress\x12A\n" +
	"\x0esent_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rsentTimestamp\x12I\n" +
	"\x12received_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11receivedTimestamp\"b\n" +
	"\x0eICMPNextHeader\x12&\n" +
	"\x0ffirst_half_word\x18\x01 \x01(\rR\rfirstHalfWord\x12(\n" +
	"\x10second_half_word\x18\x02 \x01(\rR\x0esecondHalfWord\"[\n" +
	"\rUDPNextHeader\x12\x1f\n" +
	"\vsource_port\x18\x01 \x01(\rR\n" +
	"sourcePort\x12)\n" +
	"\x10destination_port\x18\x02 \x01(\rR\x0fdestinationPort\"d\n" +
	"\x10ICMPv6NextHeader\x12&\n" +
	"\x0ffirst_half_word\x18\x01 \x01(\rR\rfirstHalfWord\x12(\n" +
	"\x10second_half_word\x18\x02 \x01(\rR\x0esecondHalfWord\"\xe8\x01\n" +
	"\n" +
	"NextHeader\x12C\n" +
	"\x10icmp_next_header\x18\x01 \x01(\v2\x17.wire.v2.ICMPNextHeaderH\x00R\x0eicmpNextHeader\x12@\n" +
	"\x0fudp_next_header\x18\x02 \x01(\v2\x16.wire.v2.UDPNextHeaderH\x00R\rudpNextHeader\x12I\n" +
	"\x12icmpv6_next_header\x18\x03 \x01(\v2\x19.wire.v2.ICMPv6NextHeaderH\x00R\x10icmpv6NextHeaderB\b\n" +
	"\x06header\"@\n" +
	"\vAuthRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"N\n" +
	"\fAuthResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc3\x02\n" +
	"\x10ProbingDirective\x120\n" +
	"\x14probing_directive_id\x18\x01 \x01(\x04R\x12probingDirectiveId\x121\n" +
	"\n" +
	"ip_version\x18\x02 \x01(\x0e2\x12.wire.v2.IPVersionR\tipVersion\x12-\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x11.wire.v2.ProtocolR\bprotocol\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\tR\x12destinationAddress\x12\x19\n" +
	"\bnear_ttl\x18\x06 \x01(\rR\anearTtl\x124\n" +
	"\vnext_header\x18\a \x01(\v2\x13.wire.v2.NextHeaderR\n" +
	"nextHeader\"\xce\x03\n" +
	"\x15ForwardingInfoElement\x12$\n" +
	"\x05agent\x18\x01 \x01(\v2\x0e.wire.v2.AgentR\x05agent\x120\n" +
	"\x14probing_directive_id\x18\x02 \x01(\x04R\x12probingDirectiveId\x121\n" +
	"\n" +
	"ip_version\x18\x03 \x01(\x0e2\x12.wire.v2.IPVersionR\tipVersion\x12-\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x11.wire.v2.ProtocolR\bprotocol\x12%\n" +
	"\x0esource_address\x18\x05 \x01(\tR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x06 \x01(\tR\x12destinationAddress\x12*\n" +
	"\tnear_info\x18\a \x01(\v2\r.wire.v2.InfoR\bnearInfo\x12(\n" +
	"\bfar_info\x18\b \x01(\v2\r.wire.v2.InfoR\afarInfo\x12M\n" +
	"\x14production_timestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x13productionTimestamp*Q\n" +
	"\tIPVersion\x12\x1a\n" +
	"\x16IP_VERSION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fIP_VERSION_IPV4\x10\x04\x12\x13\n" +
	"\x0fIP_VERSION_IPV6\x10\x06*^\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROTOCOL_ICMP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x11\x12\x13\n" +
	"\x0fPROTOCOL_ICMPV6\x10:B3Z1github.com/dioptra-io/retina-commons/wire/v2;wireb\x06proto3"

var (
	file_wire_v2_wire_proto_rawDescOnce sync.Once
	file_wire_v2_wire_proto_rawDescData []byte
)

func file_wire_v2_wire_proto_rawDescGZIP() []byte {
	file_wire_v2_wire_proto_rawDescOnce.Do(func() {
		file_wire_v2_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_v2_wire_proto_rawDesc), len(file_wire_v2_wire_proto_rawDesc)))
	})
	return file_wire_v2_wire_proto_rawDescData
}

var file_wire_v2_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wire_v2_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wire_v2_wire_proto_goTypes = []any{
	(IPVersion)(0),                // 0: wire.v2.IPVersion
	(Protocol)(0),                 // 1: wire.v2.Protocol
	(*Agent)(nil),                 // 2: wire.v2.Agent
	(*Info)(nil),                  // 3: wire.v2.Info
	(*ICMPNextHeader)(nil),        // 4: wire.v2.ICMPNextHeader
	(*UDPNextHeader)(nil),         // 5: wire.v2.UDPNextHeader
	(*ICMPv6NextHeader)(nil),      // 6: wire.v2.ICMPv6NextHeader
	(*NextHeader)(nil),            // 7: wire.v2.NextHeader
	(*AuthRequest)(nil),           // 8: wire.v2.AuthRequest
	(*AuthResponse)(nil),          // 9: wire.v2.AuthResponse
	(*ProbingDirective)(nil),      // 10: wire.v2.ProbingDirective
	(*ForwardingInfoElement)(nil), // 11: wire.v2.ForwardingInfoElement
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_wire_v2_wire_proto_depIdxs = []int32{
	12, // 0: wire.v2.Info.sent_timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: wire.v2.Info.received_timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: wire.v2.NextHeader.icmp_next_header:type_name -> wire.v2.ICMPNextHeader
	5,  // 3: wire.v2.NextHeader.udp_next_header:type_name -> wire.v2.UDPNextHeader
	6,  // 4: wire.v2.NextHeader.icmpv6_next_header:type_name -> wire.v2.ICMPv6NextHeader
	0,  // 5: wire.v2.ProbingDirective.ip_version:type_name -> wire.v2.IPVersion
	1,  // 6: wire.v2.ProbingDirective.protocol:type_name -> wire.v2.Protocol
	7,  // 7: wire.v2.ProbingDirective.next_header:type_name -> wire.v2.NextHeader
	2,  // 8: wire.v2.ForwardingInfoElement.agent:type_name -> wire.v2.Agent
	0,  // 9: wire.v2.ForwardingInfoElement.ip_version:type_name -> wire.v2.IPVersion
	1,  // 10: wire.v2.ForwardingInfoElement.protocol:type_name -> wire.v2.Protocol
	3,  // 11: wire.v2.ForwardingInfoElement.near_info:type_name -> wire.v2.Info
	3,  // 12: wire.v2.ForwardingInfoElement.far_info:type_name -> wire.v2.Info
	12, // 13: wire.v2.ForwardingInfoElement.production_timestamp:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_wire_v2_wire_proto_init() }
func file_wire_v2_wire_proto_init() {
	if File_wire_v2_wire_proto != nil {
		return
	}
	file_wire_v2_wire_proto_msgTypes[5].OneofWrappers = []any{
		(*NextHeader_IcmpNextHeader)(nil),
		(*NextHeader_UdpNextHeader)(nil),
		(*NextHeader_Icmpv6NextHeader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_v2_wire_proto_rawDesc), len(file_wire_v2_wire_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_v2_wire_proto_goTypes,
		DependencyIndexes: file_wire_v2_wire_proto_depIdxs,
		EnumInfos:         file_wire_v2_wire_proto_enumTypes,
		MessageInfos:      file_wire_v2_wire_proto_msgTypes,
	}.Build()
	File_wire_v2_wire_proto = out.File
	file_wire_v2_wire_proto_goTypes = nil
	file_wire_v2_wire_proto_depIdxs = nil
}
